In [5]:
class Employee:
    total_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.total_employees += 1

    def average_salary(self, employee_list):
        total_salary = 0
        for e in employee_list:
            total_salary += e.salary
        return total_salary / len(employee_list)

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

# Creating instances of Employee and FulltimeEmployee classes
employee1 = Employee("John Doe", "Family A", 60000, "HR")
employee2 = Employee("Jane Smith", "Family B", 55000, "IT")
fulltime_employee1 = FulltimeEmployee("Alice Johnson", "Family C", 70000, "Finance")

# Calling member functions
employees = [employee1, employee2, fulltime_employee1]
avg_salary = employee1.average_salary(employees)
print(f"Average salary: ${avg_salary:.2f}")
print(f"Total employees: {Employee.total_employees}")


Average salary: $61666.67
Total employees: 3


In [6]:
import numpy as np

random_vector = np.random.uniform(1, 20, size=20)

print("original vector : ",random_vector)

reshaped_array = random_vector.reshape(4, 5)

reshaped_array[np.arange(reshaped_array.shape[0]), np.argmax(reshaped_array, axis=1)] = 0

print("Original reshaped array:")
print(reshaped_array)

original vector :  [ 1.26670721 17.49830639  1.63418369 16.4350893   4.41289524 18.57978106
 12.13937611 15.33188004  4.45576302  3.94208022 13.55341899 17.55979618
  8.99605818  9.08687115 15.01215221  6.23509759  2.89025161  8.56043357
 15.2165156   1.12521565]
Original reshaped array:
[[ 1.26670721  0.          1.63418369 16.4350893   4.41289524]
 [ 0.         12.13937611 15.33188004  4.45576302  3.94208022]
 [13.55341899  0.          8.99605818  9.08687115 15.01215221]
 [ 6.23509759  2.89025161  8.56043357  0.          1.12521565]]
